/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Cell: typeof import('./components/lib/Cell/index.vue')['default']
    CellConfig: typeof import('./components/lib/Cell/CellConfig.vue')['default']
    CellIndex: typeof import('./components/lib/Cell/CellIndex.vue')['default']
    CellMenuItem: typeof import('./components/lib/Cell/CellMenuItem.vue')['default']
    ChatItem: typeof import('./components/ChatItem.vue')['default']
    Config: typeof import('./components/lib/Cell/config.vue')['default']
    Editor: typeof import('./components/editor.vue')['default']
    FieldConfig: typeof import('./components/lib/Field/FieldConfig.vue')['default']
    FieldIndex: typeof import('./components/lib/Field/FieldIndex.vue')['default']
    FiledIndex: typeof import('./components/lib/Field/FiledIndex.vue')['default']
    MessageItem: typeof import('./components/MessageItem.vue')['default']
    PreviewTool: typeof import('./components/common/PreviewTool.vue')['default']
    Recode: typeof import('./components/tool/Recode.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserItem: typeof import('./components/UserItem.vue')['default']
    Van: typeof import('vant/es')['default']
    VanButton: typeof import('vant/es')['Button']
    VanC: typeof import('vant/es')['C']
    VanCell: typeof import('vant/es')['Cell']
    VanCl: typeof import('vant/es')['Cl']
    VanField: typeof import('vant/es')['Field']
    VanFo: typeof import('vant/es')['Fo']
    VanForm: typeof import('vant/es')['Form']
    VanIcon: typeof import('vant/es')['Icon']
    VanImage: typeof import('vant/es')['Image']
    VanInput: typeof import('vant/es')['Input']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanPopover: typeof import('vant/es')['Popover']
    VanSwipeCell: typeof import('vant/es')['SwipeCell']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
    VanUploader: typeof import('vant/es')['Uploader']
    Voice: typeof import('./components/tool/Voice.vue')['default']
  }
}
